version: '3.5'
services:
  article_server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8888:8080"
    depends_on:
      - article_db
    environment:
      MYSQL_HOST: "article_db:3306"
      MYSQL_DATABASE: "publiceditor"
      MYSQL_USER: "ArticleFunnelDev"
      MYSQL_PASSWORD: "TheQuickBrownFox!!123"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME}
      DATAFILES_BUCKETNAME: ${DATAFILES_BUCKETNAME}
      DATAFILES_LOCATION: ${DATAFILES_LOCATION}
  article_db:
    build:
      context: .
      dockerfile: docker/Dockerfile-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "CLoTbYDEmdNbfSxb"
      MYSQL_HOST: "localhost"
      MYSQL_DATABASE: "publiceditor"
      MYSQL_USER: "ArticleFunnelDev"
      MYSQL_PASSWORD: "TheQuickBrownFox!!123"
